# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d5ae2d438ccc6d706963d70f0519e48980b00d0feb330091bb5583c3b9f5b59945e15d239687390ec09fd362f106f134ce94da479e56003312011755178420d

test:
  secret_key_base: 199999c93d72060b1188cd1f8ad15061f70de2c209ebae8e175e6224e5a3424fd694e550bc54787cbf370cbd2ed058f49c1ee56730d42138e4f44ea59fd76c33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
